vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

        # ...
    mappings:
        emalca20_credencial:
          uri_prefix:         /submissions
          upload_destination: '%kernel.root_dir%/../public/submissions'
          namer:              vich_uploader.namer_uniqid

        emalca20_historial:
          uri_prefix:         /submissions
          upload_destination: '%kernel.root_dir%/../public/submissions'
          namer:              vich_uploader.namer_uniqid

